### ISSUE TITLE
Hi Alex

### ISSUE THREAD

**Issue by fernandobayit** [alex2844/nodejs-chrome#1]
Hi Alex. How are you?

Do you still have deeznode code?

If so, you could send for me? email: fernandogobah@gmail.com

**Comment by alex2844** [comment]
[en]
Hey.
There is no more deeznode project, now I use music on YouTube.
I wrote a script through which you can download a playlist of music on YouTube. Share?

[orig]
Привет.
Проекта deeznode больше нету, теперь пользуюсь youtube music.
Написал скрипт через который можно скачивать плейлист избранного с youtube music. Вам его скинуть?

**Comment by fernandobayit** [comment]
Okay.
Yes, share with me.

Em qua., 13 de nov. de 2019 às 04:45, Alex Smith <notifications@github.com>
escreveu:

**Comment by alex2844** [comment]
https://github.com/alex2844/youtube-music

**Comment by alex2844** [comment]
Finished release version
https://github.com/alex2844/youtube-music
